import math
import matplotlib.pyplot as plt

# =========================================================
# 1. CONSTANTS - Using ISO 2314:2009 standard conditions for gas turbine performance calculations.
# =========================================================

R_AIR = 287.0           # specific gas constant for air (J/kg-K)
G = 9.81                # gravitational acceleration (m/s^2)
P0 = 101325             # sea level pressure (Pa)
T0 = 288.15             # sea level temperature (K)
R_VAPOUR = 461.5        # specific gas constant for water vapour (J/kg-K)

ISO_T = 288.15        # ISO temperature (K)
ISO_P = 101325        # ISO pressure (Pa)
ISO_RH = 0.60         # ISO 2314 assumed relative humidity

TURBINE = {
    "name": "GE 9HA-class simplified model",
    "gt_iso_power_MW": 430, # ISO power rating for a large modern CCGT gas turbine
    "gt_iso_eff": 0.4 # ISO efficiency for an advanced CCGT gas turbine. An overall plant efficiency of around 60% is typical for modern CCGTs, so I set the gas turbine efficiency to 40% to allow for the steam cycle contribution to reach that level under ideal conditions.
}

# Notes:
# - Represents a simplified GE 9HA-class reference turbine
# - ISO rating used as baseline for relative scaling only
# - Efficiency is treated as a reference thermal efficiency, NOT a full heat rate model

# Combined cycle structure
STEAM_FRACTION = 0.5  # the proportion of additional power generated by the steam cycle relative to the gas turbine (typical for modern CCGTs)
HRSG_RECOVERY_FACTOR = 0.85  # fraction of GT exhaust energy that can be recovered by the HRSG (realistic for modern designs)

# Emissions
CO2_FACTOR = 0.35  # tCO2 emitted per MWh produced (natural gas)

# Performance sensitivities
EFF_TEMP_SENS = 0.0008 # the rate at which gas turbine efficiency decreases with increasing ambient temperature (per K)


# =========================================================
# 2. PLANT DATA
# =========================================================
# Purpose:
# Compare site-condition sensitivity across representative European CCGT locations.
#
# Engineering intent:
# - Isolate ambient condition effects (temperature, altitude, humidity)
# - Keep turbine technology constant for controlled comparison
#
# Capacity factor assumption:
# - External system-level parameter representing dispatch behaviour
# - NOT derived from thermodynamics or economics in this model
#
# Limitations:
# - Does not include fuel price dispatch optimisation
# - Does not include grid congestion or outage modelling
# =========================================================
plants = {
    "Spain - Cartagena": {"alt": 10, "temp_C": 20, "cf": 0.40, "rh": 0.65},         # Moderate capacity factor (~0.40) due to higher solar penetration and gas being displaced during daytime periods.
    "Spain - Castellón": {"alt": 20, "temp_C": 19, "cf": 0.38, "rh": 0.70},         # Similar to Cartagena, with slightly lower capacity factor due to local grid conditions and renewable integration.
    "France - Bouchain": {"alt": 35, "temp_C": 12, "cf": 0.50, "rh": 0.75},         # Bouchain's record efficiency is largely due to its advanced cycle design and optimised operation, but its moderate capacity factor reflects typical operational patterns for CCGTs in France, where nuclear and renewables dominate.
    "UK - Peterhead (Scotland)": {"alt": 5, "temp_C": 9, "cf": 0.55, "rh": 0.80},   # Higher capacity factor due to stronger grid demand for flexible gas generation in Scotland, and cooler ambient temperatures that improve performance.
    "UK - Keadby 2": {"alt": 3, "temp_C": 10, "cf": 0.60, "rh": 0.85},              # Keadby 2's high capacity factor reflects its role as a flexible peaking plant in the UK grid, and its cooler location in northern England contributes to better performance.
    "Switzerland - Alpine Node": {"alt": 430, "temp_C": 8, "cf": 0.45, "rh": 0.60}  # A fictional high-altitude site representing a cold climate location, which would benefit from higher air density and thus improved gas turbine performance, but with a moderate capacity factor reflecting the challenges of operating in alpine conditions and potential grid constraints.
}
# altitude in meters, taken from plant locations
# average annual ambient temperature in °C, estimated from local climate data
# capacity factor estimates based on typical European CCGT performance and grid conditions:
# relative humidity estimates based on local climate data, which can affect air density and thus turbine performance.
# my model assumes an economically dispatched unit, so I adjusted the capacity factor to reflect operational rather than installed behaviour.

# =========================================================
# 3. ATMOSPHERIC MODEL (ISA + MOIST AIR)
# =========================================================
# Purpose:
# Model site-specific air density variation using:
# - ISA pressure decay with altitude
# - Moist air correction using water vapour partial pressure
#
# Engineering intent:
# - Capture first-order impact of environment on compressor mass flow
# - Include humidity effects often neglected in simplified turbine models
#
# Key assumption:
# - Air treated as ideal gas mixture (dry air + vapour)
#
# Limitations:
# - No wind, turbulence, or transient weather modelling
# =========================================================

# Converting Celsius to Kelvin for temperature calculations
def c_to_k(Tc):
    return Tc + 273.15

# Pressure decreases exponentially with altitude in the ISA model, which affects air density and thus turbine performance.
def pressure_at_altitude(h):
    return P0 * math.exp(-G * h / (R_AIR * T0))

# The saturation vapour pressure of water increases with temperature, which affects the humidity and thus the density of the air. This is important for accurately modelling gas turbine performance under different ambient conditions.
def saturation_vapour_pressure(T):
    Tc = T - 273.15  # convert to Celsius
    return 610.78 * math.exp((17.27 * Tc) / (Tc + 237.3))

# The density of moist air is calculated using the partial pressures of dry air and water vapour, which is critical for determining the mass flow through the gas turbine and thus its power output. Higher humidity reduces air density, which can negatively impact turbine performance, especially in warmer climates.
def air_density(P, T, RH):
    """
    Moist air density using dry air + water vapour partial pressures
    """

    Psat = saturation_vapour_pressure(T)
    Pv = RH * Psat                 # water vapour partial pressure
    Pd = P - Pv                    # dry air partial pressure

    rho_dry = Pd / (R_AIR * T)
    rho_vap = Pv / (R_VAPOUR * T)

    return rho_dry + rho_vap

# ISO conditions provide an industry standard baseline for performance comparisons, so I calculated the density at ISO conditions to use as a reference in our turbine power model.
def iso_density():
    return air_density(ISO_P, ISO_T, ISO_RH)


# =========================================================
# 4. GAS TURBINE MODEL
# =========================================================
# Purpose:
# First-order approximation of gas turbine performance sensitivity
# to ambient conditions.
#
# Engineering intent:
# - Capture mass flow variation due to air density
# - Include simplified compressor temperature penalty
#
# Key assumption:
# - Power scales approximately with inlet mass flow (density-driven)
# - Temperature effect approximates increased compressor work
#
# What is NOT included:
# - Compressor maps
# - Variable firing temperature
# - Part-load efficiency curves
# - Blade cooling effects
# =========================================================

def gt_power(rho, rho_iso, T):
    """
    First-order model:
    - Mass flow effect via density ratio
    - Temperature penalty on compressor work
    """
    density_effect = rho / rho_iso
    temp_effect = 1 - EFF_TEMP_SENS * (T - ISO_T)

    return TURBINE["gt_iso_power_MW"] * density_effect * temp_effect

# The efficiency of the gas turbine decreases with increasing ambient temperature due to reduced air density and increased compressor work. This is a key performance sensitivity for CCGTs, especially in warmer climates.
def gt_efficiency(T):
    """
    Ambient temperature effect on compressor work
    """
    return TURBINE["gt_iso_eff"] - EFF_TEMP_SENS * (T - ISO_T)


# =========================================================
# 5. COMBINED CYCLE MODEL
# =========================================================
# Purpose:
# Approximate steam cycle contribution from gas turbine exhaust energy.
#
# Engineering intent:
# - Represent HRSG + steam turbine contribution as proportional gain
# - Capture compound benefit of higher GT exhaust energy at cold sites
#
# Key assumption:
# - Fixed steam fraction represents average plant design behaviour
#
# Limitations:
# - No pinch point analysis
# - No HRSG multi-pressure modelling
# - No steam cycle thermodynamic states
# =========================================================

# The steam cycle power is a function of the exhaust energy from the gas turbine, which is affected by the ambient conditions. The HRSG recovery factor accounts for real-world limitations in heat recovery, and the steam fraction represents the typical contribution of the steam cycle to total plant output.
def hrsg_effect(gt_power):
    """
    Exhaust energy available for steam cycle
    """
    return gt_power * HRSG_RECOVERY_FACTOR

# The total combined cycle power is the sum of the gas turbine power and the steam turbine power, which is derived from the recovered exhaust energy. This model captures how site conditions affect both components of the plant's performance.
def steam_turbine_power(gt_power):
    """
    Steam cycle is a function of recovered heat
    """
    return hrsg_effect(gt_power) * STEAM_FRACTION

# Total combined cycle power output, which is the key performance metric for the plant.
def combined_cycle_power(gt_power):
    return gt_power + steam_turbine_power(gt_power)

# =========================================================
# 6. ANNUAL ENERGY AND EMISSIONS
# =========================================================


# To translate the power output into an annual energy production figure, we multiply the combined cycle power by the capacity factor and the number of hours in a year.
def annual_energy(power_mw, capacity_factor):
    """
    MWh/year = MW * CF * hours/year
    """
    return power_mw * capacity_factor * 8760

# To calculate the annual CO2 emissions based on the energy produced, we multiply the annual energy by the CO2 factor, which represents the emissions intensity of natural gas generation.
def emissions(mwh):
    return mwh * CO2_FACTOR


# =========================================================
# 7. RUN MODEL
# =========================================================

rho_iso = iso_density()
results = []

for name, p in plants.items():              # loop through each plant and calculate performance metrics, using p to access the plant-specific parameters (altitude, temperature, capacity factor)

    T = c_to_k(p["temp_C"])                 # convert ambient temperature from Celsius to Kelvin for calculations
    P = pressure_at_altitude(p["alt"])      # calculate ambient pressure at the plant's altitude using the ISA model, which will affect air density and thus turbine performance

    rho = air_density(P, T, p["rh"])        # calculate the air density (kg/m3) at the plant's site conditions, which is a critical factor for gas turbine performance as it determines the mass flow through the compressor

    gt = gt_power(rho, rho_iso, T)          # calculate the gas turbine power output based on the site specific air density relative to ISO conditions, which captures how altitude and temperature affect performance
    cc = combined_cycle_power(gt)           # calculate the total combined cycle power output, which includes the contribution from the steam cycle based on the recovered exhaust energy

    eff = gt_efficiency(T)                  # calculate the gas turbine efficiency at the ambient temperature, which decreases with increasing temperature due to reduced air density and increased compressor work

    annual_mwh = annual_energy(cc, p["cf"]) # calculate the annual energy production in MWh/year by multiplying the combined cycle power by the capacity factor and the number of hours in a year, which translates the power output into an annual energy figure that reflects real-world operational conditions
    co2 = emissions(annual_mwh)             # calculate the annual CO2 emissions based on the energy produced, which provides insight into the environmental impact of the plant's operation under different site conditions
    humidity_factor = rho / rho_iso         # calculate the humidity impact factor as the ratio of the actual air density to the ISO density, which indicates how much the ambient humidity affects the air density and thus the turbine performance compared to standard conditions

    results.append({
        "plant": name,
        "gt_MW": gt,
        "cc_MW": cc,
        "eff": eff,
        "annual_MWh": annual_mwh,
        "co2_t": co2,
        "humidity_factor": humidity_factor
    })


# =========================================================
# 8. RESULTS
# =========================================================
# Purpose:
# Provide comparative performance outputs across sites:
# - Power output
# - Efficiency sensitivity
# - Annual energy
# - Emissions
#
# Engineering intent:
# - Enable ranking of sites under consistent turbine assumptions
#
# Important:
# - Results reflect site-condition sensitivity ONLY
# - Not absolute plant guarantees or OEM performance curves
# =========================================================

print("\n=== CCGT EUROPE PERFORMANCE SCREENING ===\n")

for r in results:
    print(r["plant"])
    print(f" GT Power: {r['gt_MW']:.2f} MW")
    print(f" CC Power: {r['cc_MW']:.2f} MW")
    print(f" Efficiency index: {r['eff']:.4f}")
    print(f" Annual Energy: {r['annual_MWh']:.0f} MWh/year")
    print(f" CO2: {r['co2_t']:.0f} t/year")
    print(f" Humidity impact factor: {r['humidity_factor']:.4f}")
    print("-" * 55)


# =========================================================
# 9. RANKING AND COMPARISON
# =========================================================

ranked = sorted(results, key=lambda x: x["annual_MWh"], reverse=True)

print("\n=== RANKING (ANNUAL ENERGY OUTPUT) ===\n")

for i, r in enumerate(ranked, 1):
    print(f"{i}. {r['plant']} → {r['annual_MWh']:.0f} MWh/year")


# =========================================================
# 10. GRAPHS
# =========================================================

names = [r["plant"] for r in results]
annual = [r["annual_MWh"] for r in results]
co2 = [r["co2_t"] for r in results]
efficiencies = [r["eff"] for r in results]

# Plotting the annual energy production for each plant to visually compare their performance. 
plt.figure()
plt.bar(names, annual)
plt.title("Annual Energy Production by Plant")
plt.ylabel("MWh/year")
plt.xticks(rotation=30)
plt.tight_layout()
plt.show()

# Plotting the annual CO2 emissions for each plant to show the environmental impact associated with their energy production.
plt.figure()
plt.bar(names, co2)
plt.title("Annual CO2 Emissions by Plant")
plt.ylabel("tCO2/year")
plt.xticks(rotation=30)
plt.tight_layout()
plt.show()

# Plotting the efficiency for each plant to compare ambient condition effects on turbine performance. 
plt.barh(names, efficiencies)
plt.title("Gas Turbine Efficiency vs Ambient Conditions")
plt.xlabel("GT Efficiency Index")
plt.tight_layout()
plt.show()

# =========================================================
# 11. ENGINEERING INSIGHT
# =========================================================

print("\n=== ENGINEERING INSIGHT ===\n")

# Identify best and worst performing sites
best = max(results, key=lambda x: x["annual_MWh"])
worst = min(results, key=lambda x: x["annual_MWh"])

print("1. Key finding:")
print(f"- Highest annual output: {best['plant']} ({best['annual_MWh']:.0f} MWh/year)")
print(f"- Lowest annual output:  {worst['plant']} ({worst['annual_MWh']:.0f} MWh/year)\n")

print("2. Physical explanation:")
print("- Cold / high-density air increases compressor mass flow")
print("- Higher mass flow → higher gas turbine power output")
print("- This increases exhaust energy available to the HRSG")
print("- Result: steam cycle output also increases → compounding effect\n")

print("3. Combined cycle behaviour:")
print("- Gas turbine is the driver of total plant performance")
print("- Steam cycle acts as a multiplier via recovered exhaust heat")
print("- Therefore small GT changes amplify at plant level\n")

print("4. Key modelling assumption:")
print("- All sites use identical turbine technology (ISO baseline)")
print("- Differences are purely driven by ambient conditions\n")

print("5. Limitation:")
print("- No part-load modelling or dispatch optimisation")
print("- No OEM-specific compressor/turbine maps")
print("- HRSG is simplified as a fixed recovery fraction\n")

print("6. Conclusion:")
print("- Site conditions alone can drive meaningful variation in")
print("  annual energy output even when plant hardware is identical.")